### ISSUE TITLE
Replace 같은데..

### ISSUE THREAD

**Issue by killerdong** [heejunghwang/movie-finder#1]
https://github.com/heejunghwang/movie-finder/blob/514fb09ce47c517c3c88be363a1fbb14f41d8523/src/api/cat.js#L34

요거 replace 인거 같은데 
```javascript
JSON.stringify(v).replace(/\./g, '_')
```
이게 더 나은 듯 한데 어떤지.

**Comment by heejunghwang** [comment]
적용완료했습니다~
