### ISSUE TITLE
ECMA2015+

### ISSUE THREAD

**Issue by killerdong** [heejunghwang/movie-finder#2]
ECMA2015+  쓸 것이면 이것도

https://github.com/heejunghwang/movie-finder/blob/514fb09ce47c517c3c88be363a1fbb14f41d8523/src/api/bulk.js#L6

```javascript
import each from 'foreach';
```
https://github.com/heejunghwang/movie-finder/blob/514fb09ce47c517c3c88be363a1fbb14f41d8523/src/api/bulk.js#L20

이런 부분은

```javascript
bulkIndex(indexName, typeName, bulkDocument) {
```
이런식으로 줄이는게 가능

https://github.com/heejunghwang/movie-finder/blob/514fb09ce47c517c3c88be363a1fbb14f41d8523/src/api/bulk.js#L33

이런건 전부 arrow 표기법으로

```javascript
return this.startBulkIndex(reqParam).then(result => { 
```

예로 이런 건
```javascript
/**
   * bulk 인덱싱 엘라스틱 서치 API 호출을 한다.
   * @param reqParam
   * @returns {Promise<any>}
   */
  startBulkIndex : function (reqParam) {
    return new Promise(function (resolve, reject) {
      elasticsearchClient.bulk({
        body: reqParam
      },function(err,resp,status) {
        if(status == '200') {
          resolve(resp);
        }else{
          reject(err);
        }
      });
    }).then(function (resp) {
      return resp;
    });
  }
```

```javascript
/**
   * bulk 인덱싱 엘라스틱 서치 API 호출을 한다.
   * @param reqParam
   * @returns {Promise<any>}
   */
  startBulkIndex(reqParam) {
    return Promise.resolve(
        (resolve, reject) => elasticsearchClient.bulk({
            body: reqParam
         },(err,resp,status) =>  status == '200' ? resp : throw err
    ));
  }
```

돌려보진 않아서 확신은... 그런데 보니 reject 처리가 없다면..
그냥 Promise.resolve 를 쓰는고 나중에 Promise.prototype.catch 를 이용해서 에러 처리하는 것도 방법..

https://github.com/heejunghwang/movie-finder/blob/514fb09ce47c517c3c88be363a1fbb14f41d8523/src/api/cat.js#L32

이런 건 그냥 

```javascript
const indexList = []; 
```

let은 재할당이 있는 경우에만 사용하고(거의 없음) 그 외에는 const를 사용하는  것 나중에 재할당 실수로 프로그램이 잘못되는 것을 막을 수 있음

**Comment by heejunghwang** [comment]
적용완료했습니다~
